[[redirects]]
  from = "https://playtictactoe-page.netlify.app/*"
  to = "https://playtictactoe.page/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
